### PR TITLE
Create install-requirements-ubuntu and added missing dependency

### PR DESCRIPTION
**Pull request by copeland3300**
Also added an additional dependency to stop the canberra-gtk-module error from showing

### CODE REVIEW

**Comment by tliron** [comment]
Hi @copeland3300, any way we can integrate this into the Debian script for simplicity? I'm worried about having to maintain dozens of scripts for everybody's favorite variant...

**Comment by rbreaves** [comment]
You can steal this from me if you'd like, I hand off to it a lot..

https://github.com/rbreaves/kinto/blob/master/system-config/unipkg.sh

**Comment by tliron** [comment]
Thank @rbreaves , but the issue is that the package names are very different in the different OSes.

**Comment by rbreaves** [comment]
I’m aware of that, why I call it from a different script I have that contains the different names for the top 3 or 4 distros out there.

```
typeset -l distro
distro=$(awk -F= '$1=="NAME" { print $2 ;}' /etc/os-release)
```

https://github.com/rbreaves/kinto/blob/master/xkeysnail_service.sh

I also have to account for DE’s as well & you could confirm compatibility too, if you don’t already.

**Pull request closed without merging**
